# ============================================
# This file should be places in ~/.specutils
# ===========================================
# read an Arecibo Legacy Fast ALFA Survey spectrum
# http://egg.astro.cornell.edu/alfalfa/  
# ASCII Table format
#
# Format is an # delimited header followed by 5 columns of data.
# So metadata need to be parsed from this header.
# Example:
# 
#Observatory:    Arecibo Observatory
#Telescope:      Arecibo Radio Telescope
#Instrument:     ALFA (L-band feed array)
#Beam size:      3.3x3.8 [arcminutes]
#NaNvalue        -999.
#AGC#-ID:        6654
#Common name:    N3815...
#HIsrcname:      HI114139.6+244802
#GRIDname:       1140+25b
#HI_RA:           175.41499  (J2000) decimal degrees
#HI_DEC:           24.80083  (J2000) decimal degrees
#OC_RA:           175.41292  (J2000) decimal degrees
#OC_DEC:           24.80000  (J2000) decimal degrees
#Use_RA:          175.41292  (J2000) decimal degrees
#Use_DEC:          24.80000  (J2000) decimal degrees
#Equinox:        2000.0
#Rest Frequency: 1.4204058e+09 [Hz]
#Bandwidth:      24.975586 [MHz]
#Channels:       1024
#V21sys:         3713  (km/s)
#Detection Code:    1
#Category:       highSNR
#Data archive at http://egg.astro.cornell.edu/alfalfa/data
#Data from the ALFALFA HI Survey a.100 Release Date 2018
#File generated by M.P. Haynes  Tue Mar 13 18:10:29 2018
#This spectrum has been baseline subtracted.
#Table FORMAT:  (f8.1,1x,f12.6,1x,f12.4,1x,f12.4,1x,f12.4)
#
#Column descriptions:
# 1. Heliocentric velocity [km/s]
# 2. Radio frequency [MHz]
# 3. Flux Density [mJy]
# 4. Subtracted polynomial baseline fit [mJy]
# 5. Normalized spectral weight
#
####################################################################
#
#  7956.8  1383.681637      -0.6090      -0.2059       1.0000

import os

from astropy.nddata import StdDevUncertainty
from astropy.table import QTable
from astropy.wcs import WCS
import astropy.units as u

from specutils.io.registers import data_loader
from specutils import Spectrum

_valid_ext = ['.txt','.tab']
def identify_alfa_txt(origin,*args,**kwargs):
    filename = args[0]
    ext = os.path.splitext(filename.lower())[1]
    if extgood not in _valid_ext:
        print(f"### Unrecognized extension {ext} of file, expecting {_valid_ext}")
        return False
    # check first line of file 
    with open(filename,"r") as file:
        line = file.readline()
        if "Arecibo Legacy Fast ALFA Survey" not in lines[0]:
            print(f"### This file is not tagged as ALFA Survey.  Requires 'Arecibo Legacy Fast ALFA Survey' in first line")
            return False
    return True

@data_loader("alfa",identifier=identify_alfa_txt,extensions=_valid_ext)
def load_alfa_spectrum(filename,**kwargs):
    meta,col,unit = parse_meta(filename)
    # Use a Qtable so that columns are already Quantities for Spectrum constructor
    tab = QTable.read(filename,format='ascii', names=col, units=unit)
    tab.meta = meta
    flux = tab['Flux Density']
    spa = tab['Radio frequency']
    return Spectrum(flux=flux,spectral_axis=spa,meta=meta)

def parse_meta(filename:str)->dict:
    _expected_header =  [
        'Observatory',
        'Telescope',        
        'Instrument',         
        'Beam size',        
        'NaNvalue',               
        'AGC#-ID',
        'Common name',
        'HIsrcname',
        'GRIDname',
        'HI_RA',
        'HI_DEC',
        'OC_RA',
        'OC_DEC',
        'Use_RA',
        'Use_DEC',
        'Equinox',
        'Rest Frequency',
        'Bandwidth',
        'Channels',
        'V21sys',
        'Detection Code',
        'Category',
    ]
    meta = {}
    i = 0
    col = []
    unit =[]
    with open(filename,"r") as file:
        lines = file.readlines()
        for line in lines:
            if "Column descriptions" in line:
                col,unit = parse_columns(lines[i+1:i+6])
            elif line.startswith('#'):
                keyval = line.split(':',1)
                if len(keyval) == 2 and keyval[0][1:] in _expected_header:
                    meta[keyval[0][1:]] = keyval[1]
            i=i+1
    # add these to meta for completeness
    for i in range(len(col)):
        meta[col[i]] = unit[i]
                
    return meta,col,unit

def parse_columns(column_descriptions:list)->dict:
    col =[]
    unit = []
    for c in column_descriptions:
        a,b = c.split('.',1)
        d = b.split('[')
        col.append(d[0].strip())
        if len(d) == 2:
            unit.append( d[1].split(']')[0])
        else:
            unit.append('')
    return col,unit
