#! /usr/bin/env bash
#
#--HELP
# default parameters

wget=wgetc                                         # ideally use caching wgetc if you have it
url=https://github.com/GreenbankObservatory/dysh   # official repo
restart=1                                          # re-install old anaconda3 and dysh?
sleep=5                                            # enforced sleep to prevent accidents
uv=0                                               # base the install of dysh on 'uv'
pytest=0                                           # run pytest
    
#--HELP


# some help?    
 if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    set +x
    awk 'BEGIN{s=0} {if ($1=="#--HELP") s=1-s;  else if(s) print $0; }' $0
    exit 0
fi
   
# override parameters
for arg in "$@"; do
  export "$arg"
done

# sleep protection
echo Sleeping $sleep
sleep $sleep

if [ $restart = 1 ]; then
    rm -rf anaconda3
    ./install_anaconda3 wget=$wget
fi
source anaconda3/python_start.sh


if [ $restart = 1 ]; then
    rm -rf dysh
    git clone $url dysh
fi

cd dysh

if [ $uv = 1 ]; then
    pip install uv
    uv synv
    echo "Running via:"
    echo "    uv run dysh"
    echo "or"
    echo "    uv run dysh-lab"
else
    pip install -e .[all]
fi


# if we want the test - note test_notebooks.py always take long...

if [ $pytest = 1 ]; then
    pytest
fi
