#! /usr/bin/env bash
#     example dysh install
#     1)   just install anaconda + dysh        ~ 1-2 min
#     2)   pytest                              ~ 5 min
#     3)   docs/source                         ~ 4 min
#
#  Install examples:
#     ./install_dysh docs=1 version=-1 venv=1
#     ./install_dysh docs=1 uv=1
#     ./install_dysh docs=1
#
#  Examples:
#     uvx dysh --no-banner
#     uvx --from dysh[all] dysh-lab
#     uv tool install dysh[all]
#
#  Tested:
#                        3.10.14   fails pytest
#     version=2024.02-1  3.11.7    ok
#     version=2024.10-1  3.12.7    ok
#     version=2025.06-1  3.13.5    (in numpy_2)
#
#--HELP
# default parameters

wget=wgetc                                         # ideally use caching wgetc if you have it
url=https://github.com/GreenbankObservatory/dysh   # official repo
restart=1                                          # re-install old anaconda3 and dysh?
sleep=5                                            # enforced sleep to prevent accidents
uv=0                                               # base the install of dysh on 'uv'?
venv=0                                             # use a venv in your existing python
pytest=0                                           # run pytest?
docs=0                                             # build documentation?
pr=0                                               # merge in a PR?
version=0                                          # specific anaconda3 version (-1 to skip)
    
#--HELP


# some CLI help?
 if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    set +x
    awk 'BEGIN{s=0} {if ($1=="#--HELP") s=1-s;  else if(s) print $0; }' $0
    exit 0
fi
   
# override parameters from CLI
for arg in "$@"; do
  export "$arg"
done

# sleep protection
echo Sleeping $sleep
sleep $sleep

if [ $version = -1 ]; then
    echo no anaconda3, you must/should use venv=1
else
    if [ $restart = 1 ]; then
	rm -rf anaconda3
	if [ $version = 0 ]; then
	    version=""
	else
	    version="version=$version"
	fi
	echo ./install_anaconda3 wget=$wget $version
	./install_anaconda3 wget=$wget $version    # e.g. version=2023.03-1
    fi
    if [ -e anaconda3/python_start.sh ]; then
	source anaconda3/python_start.sh
    fi
fi

if [ $venv = 1 ]; then
    rm -rf venv
    python -m venv venv
    source venv/bin/activate
fi


if [ $restart = 1 ]; then
    rm -rf dysh
    git clone $url dysh
fi

cd dysh

if [ $uv = 1 ]; then
    pip3 install uv
    #uv sync # --active
    uv sync --all-extras
    # activate, or do all with "uv run" etc.
    source .venv/bin/activate
    echo "Running via:"
    echo "    uv run dysh"
    echo "or"
    echo "    uv run dysh-lab"
else
    pip3 install --upgrade pip
    pip3 install --group dev -e .
fi

if [ $pr != 0 ]; then
    echo "NOTE: Merging in origin/$pr"
    git merge origin/$pr
fi


# if we want the test - note test_notebooks.py always take long...
if [ $pytest = 1 ]; then
    pytest
fi

# building docs - see results in docs/source/_build/html/index.html
# again, the notebooks take a long time (they need to be executed)
if [ $docs = 1 ]; then
    (cd docs/source; make html)
    echo Documentation in $pwd/docs/source/_build/html/index.html
fi
